//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using UnitsNet.NumberExtensions.NumberToStandardFlow;
using Xunit;

namespace UnitsNet.Tests
{    
    public class NumberToStandardFlowExtensionsTests
    {
        [Fact]
        public void NumberToStandardCubicCentimetersPerMinuteTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicCentimetersPerMinute(2), 2.StandardCubicCentimetersPerMinute());

        [Fact]
        public void NumberToStandardCubicCentimetersPerSecondTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicCentimetersPerSecond(2), 2.StandardCubicCentimetersPerSecond());

        [Fact]
        public void NumberToStandardCubicDecimetersPerMinuteTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicDecimetersPerMinute(2), 2.StandardCubicDecimetersPerMinute());

        [Fact]
        public void NumberToStandardCubicFeetPerDayTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicFeetPerDay(2), 2.StandardCubicFeetPerDay());

        [Fact]
        public void NumberToStandardCubicFeetPerHourTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicFeetPerHour(2), 2.StandardCubicFeetPerHour());

        [Fact]
        public void NumberToStandardCubicFeetPerMinuteTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicFeetPerMinute(2), 2.StandardCubicFeetPerMinute());

        [Fact]
        public void NumberToStandardCubicFeetPerSecondTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicFeetPerSecond(2), 2.StandardCubicFeetPerSecond());

        [Fact]
        public void NumberToStandardCubicMetersPerDayTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicMetersPerDay(2), 2.StandardCubicMetersPerDay());

        [Fact]
        public void NumberToStandardCubicMetersPerHourTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicMetersPerHour(2), 2.StandardCubicMetersPerHour());

        [Fact]
        public void NumberToStandardCubicMetersPerMinuteTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicMetersPerMinute(2), 2.StandardCubicMetersPerMinute());

        [Fact]
        public void NumberToStandardCubicMetersPerSecondTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicMetersPerSecond(2), 2.StandardCubicMetersPerSecond());

        [Fact]
        public void NumberToStandardCubicMillimetersPerSecondTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicMillimetersPerSecond(2), 2.StandardCubicMillimetersPerSecond());

        [Fact]
        public void NumberToStandardCubicYardsPerDayTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicYardsPerDay(2), 2.StandardCubicYardsPerDay());

        [Fact]
        public void NumberToStandardCubicYardsPerHourTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicYardsPerHour(2), 2.StandardCubicYardsPerHour());

        [Fact]
        public void NumberToStandardCubicYardsPerMinuteTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicYardsPerMinute(2), 2.StandardCubicYardsPerMinute());

        [Fact]
        public void NumberToStandardCubicYardsPerSecondTest() =>
            Assert.Equal(StandardFlow.FromStandardCubicYardsPerSecond(2), 2.StandardCubicYardsPerSecond());

    }
}
